"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

const services = [
  { no: "01", name: "Landing Pages", text: "Páginas enfocadas en convertir atención en oportunidades reales.", detail: "Para campañas, productos, servicios o negocios que necesitan captar clientes rápidamente." },
  { no: "02", name: "Web Corporativa", text: "Una presencia digital a la altura de la empresa que ya construiste.", detail: "Estructuramos tu información, servicios y proyectos para comunicar con claridad y confianza." },
  { no: "03", name: "Catálogos Virtuales", text: "De un PDF compartido a una experiencia que tus clientes pueden explorar.", detail: "Categorías, productos e información centralizada en un catálogo digital navegable." },
  { no: "04", name: "Herramientas de Gestión", text: "Sistemas que ordenan la operación y devuelven control al negocio.", detail: "Inventario, ventas, clientes, reportes y procesos empresariales en herramientas hechas a medida." },
];

export function ServicesExplorer() { const [active, setActive] = useState(0); const current = services[active]; return <div className="service-explorer"><div className="explorer-nav" role="tablist" aria-label="Explorar servicios">{services.map((service, i) => <button key={service.no} className={i === active ? "active" : ""} onClick={() => setActive(i)} role="tab" aria-selected={i === active}><span>{service.no}</span>{service.name}</button>)}</div><div className="explorer-panel" role="tabpanel"><span className="service-no">{current.no} / SERVICIO</span><h2>{current.name}</h2><p>{current.detail}</p><div className="service-tags">{["Estrategia", "Diseño", "Desarrollo", "Responsive"].map(tag => <span key={tag}>{tag}</span>)}</div><div className="explorer-index"><span>0{active + 1}</span><span>/ 04</span></div></div></div>; }

export function HomeServices() { const [active, setActive] = useState(0); const current = services[active]; return <section className="services-preview"><div className="container"><div className="section-heading"><div><span className="eyebrow">Lo que construimos</span><h2 className="section-title">Diseño que<br /><span className="orange">hace avanzar.</span></h2></div><p>Desde una primera impresión clara hasta sistemas que sostienen tu operación. Elegimos la solución que el negocio realmente necesita.</p></div><div className="service-switcher"><div className="service-tabs" role="tablist" aria-label="Servicios FORM4TH">{services.map((service, i) => <button className={`service-tab ${i === active ? "active" : ""}`} key={service.no} onClick={() => setActive(i)} role="tab" aria-selected={i === active}><small>{service.no}</small><span>{service.name}</span><span>↗</span></button>)}</div><div className="service-panel" role="tabpanel"><span className="panel-number">/ {current.no} — {current.name}</span><h3>{current.text}</h3><p>{current.detail}</p><div className="panel-lines" aria-hidden="true">{services.map((_, i) => <span key={i} style={{ background: i === active ? "var(--orange)" : undefined }} />)}</div><Link className="text-link" href="/servicios">Ver todos los servicios</Link></div></div></div></section>; }

export function HomeProjects() { return <section className="project-preview"><div className="container"><div className="section-heading"><div><span className="eyebrow">Trabajo seleccionado</span><h2 className="section-title">Proyectos<br /><span className="orange">con propósito.</span></h2></div><p>Dos formas de transformar una necesidad concreta en una experiencia digital que trabaja todos los días.</p></div><div className="project-list"><Link className="project-card" href="/proyectos/acm-diproyec"><small>01 / WEB</small><h3>ACM Diproyec</h3><p>Presencia corporativa para una empresa constructora.</p><span className="project-arrow">↗</span></Link><Link className="project-card" href="/proyectos/estampado-djhonny"><small>02 / CATÁLOGO</small><h3>Estampado D&apos;Jhonny</h3><p>Un catálogo digital para explorar productos sin fricción.</p><span className="project-arrow">↗</span></Link></div><div style={{ marginTop: 38 }}><Link className="text-link" href="/proyectos">Explorar proyectos</Link></div></div></section>; }

export function Pillars() { const items = [["01", "PRESENCE", "Una presencia digital profesional que abre la puerta correcta."], ["02", "CLARITY", "Información organizada para que clientes y equipos encuentren el camino."], ["03", "CONTROL", "Herramientas que la empresa puede administrar y hacer propias."], ["04", "PROGRESS", "Tecnología preparada para acompañar el crecimiento."]]; return <section className="pillars"><div className="container"><div className="section-heading"><div><span className="eyebrow">La forma FORM4TH</span><h2 className="section-title">Cuatro ideas.<br /><span className="orange">Una dirección.</span></h2></div><p>Un producto digital vale por lo que hace posible después de publicarlo.</p></div><div className="pillar-grid">{items.map(([no, title, text]) => <div className="pillar" key={no}><span className="pillar-no">{no}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>; }

export function Approach() { const steps = [["01", "ENTENDEMOS", "Conocemos cómo funciona tu negocio y qué necesita resolver."], ["02", "DEFINIMOS", "Diseñamos estructura, solución y alcance antes de construir."], ["03", "CONSTRUIMOS", "Diseño y desarrollo con foco en una experiencia clara."], ["04", "ENTREGAMOS", "Publicamos y dejamos la solución preparada para utilizarse."]]; return <section className="approach"><div className="container"><span className="eyebrow">Método de trabajo</span><div className="approach-content"><div className="approach-big">Pensar.<br />Diseñar.<br /><span>Hacer.</span></div><div className="steps">{steps.map(([no, title, text]) => <div className="step" key={no}><span className="step-no">{no}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></div></section>; }

export function TechStack() { const groups = [["Frontend", "React\nNext.js\nTypeScript"], ["Backend", "Python\nNode.js\nJava"], ["Datos", "PostgreSQL\nMySQL\nSupabase"], ["Cloud", "Vercel\nCloudflare\nAzure"]]; return <section className="tech-section"><div className="container"><span className="eyebrow">Stack de respaldo</span><div className="tech-layout"><div className="tech-copy"><h2>Tecnología<br /><span className="orange">cuando importa.</span></h2><p>La herramienta adecuada para que la solución sea estable, escalable y fácil de usar. La tecnología acompaña la idea: no la tapa.</p></div><div className="tech-groups">{groups.map(([title, value]) => <div className="tech-group" key={title}><h3>{title}</h3><div>{value.split("\n").map(line => <div key={line}>{line}</div>)}</div></div>)}</div></div></div></section>; }

export function BeforeAfter() { const items = [["PDF por WhatsApp", "Catálogo navegable"], ["Información dispersa", "Web centralizada"], ["Consultas repetitivas", "Información disponible 24/7"], ["Procesos manuales", "Herramientas digitales"], ["Dependencia técnica", "Mayor control"]]; const [active, setActive] = useState(0); return <section className="before-after"><div className="container"><div className="section-heading"><div><span className="eyebrow">El cambio</span><h2 className="section-title">No se trata solo<br />de <span className="orange">verse mejor.</span></h2></div><p>Se trata de hacer que la información, los procesos y las oportunidades estén disponibles cuando el negocio los necesita.</p></div><div className="ba-grid">{items.map(([before, after], i) => <button className={`ba-item ${i === active ? "after" : "before"}`} key={before} onClick={() => setActive(i)}><small>{i === active ? "FORM4TH" : "ANTES"}</small><h3>{i === active ? after : before}</h3></button>)}</div><p style={{ margin: "28px 0 0", color: "#92928d", font: "11px var(--font-mono)", textTransform: "uppercase" }}>Selecciona una transformación para explorarla · {String(active + 1).padStart(2, "0")} / {String(items.length).padStart(2, "0")}</p></div></section>; }

export function ProjectHero({ type, title, image, external, externalLabel }: { type: string; title: string; image: string; external: string; externalLabel: string }) { return <section className="case-hero"><div className="container"><div className="case-top"><div><span className="eyebrow">Caso de estudio / {type}</span><h1>{title}</h1></div><div className="case-summary">Una necesidad concreta convertida en una experiencia digital más clara, accesible y preparada para el día a día.<br /><br /><a className="button button-orange" href={external} target="_blank" rel="noopener noreferrer">{externalLabel}</a></div></div><div className={`case-image ${title.includes("ACM") ? "acm" : "dj"}`}><Image src={image} alt={`Proyecto ${title}`} fill sizes="(max-width: 700px) 100vw, 1180px" priority /><div className="case-image-overlay"><span>FORM4TH / 2025</span><span>Scroll to explore ↓</span></div></div></div></section>; }

export function CasePreview({ label }: { label: string }) { return <section className="case-preview"><div className="container"><div className="case-preview-top"><span className="eyebrow">Diseño / Vista previa</span><span className="preview-note">Capturas del producto · placeholder temporal</span></div><div className="preview-frame"><Image src="/images/bambi.jpeg" alt={`Placeholder de capturas para ${label}`} fill sizes="(max-width: 700px) 100vw, 980px" /><div className="preview-window"><span /><span /><span /><b>{label}</b></div><div className="preview-label">BAMBI / REEMPLAZAR CON CAPTURAS</div></div></div></section>; }
