"use client";

import Image from "next/image";
import { useState } from "react";
import { KeyboardButton } from "./keyboard/KeyboardButton";

const services = [
  { no: "01", group: "PRESENCIA", name: "Landing pages", text: "Haz que tu empresa se vea tan profesional como realmente es.", detail: "Landing pages, webs corporativas y catálogos virtuales para comunicar mejor y convertir visitas en oportunidades.", tags: ["Landing pages", "Web corporativa", "Catálogos"] },
  { no: "02", group: "SISTEMAS", name: "Productos digitales", text: "Software construido alrededor de cómo funciona tu negocio.", detail: "Sistemas web, herramientas internas y automatizaciones que ordenan la operación y devuelven control.", tags: ["Sistemas web", "Gestión", "Automatización"] },
];

export function ServicesExplorer() { const [active, setActive] = useState(0); const current = services[active]; return <div className="service-explorer"><div className="explorer-nav" role="tablist" aria-label="Explorar servicios">{services.map((service, i) => <KeyboardButton key={service.no} variant="normal" className={`explorer-key ${i === active ? "active" : ""}`} label={`${service.no} ${service.group}`} onPress={() => setActive(i)} role="tab" aria-selected={i === active}><span className="explorer-key-number">{service.no}</span><span>{service.group}</span><b>↗</b></KeyboardButton>)}</div><div className="explorer-panel" role="tabpanel"><span className="service-no">{current.no} / {current.group}</span><h2>{current.name}</h2><p>{current.detail}</p><div className="service-tags">{current.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="explorer-index"><span>0{active + 1}</span><span>/ 02</span></div></div></div>; }

export function HomeServices() { const [active, setActive] = useState(0); const current = services[active]; return <section className="services-preview"><div className="container"><div className="section-heading"><div><span className="eyebrow">Lo que construimos</span><h2 className="section-title">Presencia.<br /><span className="orange">Sistemas.</span></h2></div><p>Dos caminos digitales para que tu negocio comunique mejor o funcione con más control.</p></div><div className="service-switcher"><div className="service-tabs" role="tablist" aria-label="Servicios FORM4TH">{services.map((service, i) => <KeyboardButton variant="normal" className={`service-tab ${i === active ? "active" : ""}`} key={service.no} onPress={() => setActive(i)} role="tab" aria-selected={i === active} label={`${service.no} ${service.group}`}><span>{service.no}</span><span>{service.group}</span><span>↗</span></KeyboardButton>)}</div><div className="service-panel" role="tabpanel"><span className="panel-number">/ {current.no} — {current.group}</span><h3>{current.text}</h3><p>{current.detail}</p><div className="service-tags">{current.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="panel-lines" aria-hidden="true">{services.map((_, i) => <span key={i} style={{ background: i === active ? "var(--forth-orange)" : undefined }} />)}</div><KeyboardButton variant="enter" className="text-link key-link" href="/servicios" label="Ver servicios" /></div></div></div></section>; }

export function HomeProjects() { return <section className="project-preview"><div className="container"><div className="section-heading"><div><span className="eyebrow">Trabajo seleccionado</span><h2 className="section-title">Proyectos<br /><span className="orange">en práctica.</span></h2></div><p>Necesidades concretas convertidas en experiencias digitales que trabajan todos los días.</p></div><div className="project-cards"><article className="project-visual-card acm-card"><div className="project-visual"><Image src="/images/captura1-acmdiproyec.png" alt="Vista previa de la web de ACM Diproyec" fill sizes="(max-width: 700px) 100vw, 50vw" /></div><div className="project-card-meta"><small>01 / WEB CORPORATIVA</small><KeyboardButton variant="enter" href="/proyectos/acm-diproyec" label="Abrir ACM Diproyec" /></div><h3>ACM Diproyec</h3></article><article className="project-visual-card dj-card"><div className="project-visual"><Image src="/images/captura1-djhonny.png" alt="Vista previa del catálogo de Estampado D'Jhonny" fill sizes="(max-width: 700px) 100vw, 50vw" /></div><div className="project-card-meta"><small>02 / CATÁLOGO VIRTUAL</small><KeyboardButton variant="enter" href="/proyectos/estampado-djhonny" label="Abrir Estampado D'Jhonny" /></div><h3>Estampado D&apos;Jhonny</h3></article></div><div style={{ marginTop: 38 }}><KeyboardButton variant="space" className="text-link key-link" href="/proyectos" label="Explorar proyectos" /></div></div></section>; }

export function StudioNote() { return <section className="studio-note"><div className="container studio-note-grid"><span className="eyebrow">La idea detrás de FORM4TH</span><div><h2>La tecnología tiene sentido cuando <span>hace visible lo que ya funciona.</span></h2><KeyboardButton variant="enter" className="text-link key-link" href="/contacto" label="Empecemos" /></div></div></section>; }

export function Pillars() { const items = [["01", "PRESENCE", "Una presencia digital profesional que abre la puerta correcta."], ["02", "CLARITY", "Información organizada para que clientes y equipos encuentren el camino."], ["03", "CONTROL", "Herramientas que la empresa puede administrar y hacer propias."], ["04", "PROGRESS", "Tecnología preparada para acompañar el crecimiento."]]; return <section className="pillars"><div className="container"><div className="section-heading"><div><span className="eyebrow">La forma FORM4TH</span><h2 className="section-title">Cuatro ideas.<br /><span className="orange">Una dirección.</span></h2></div><p>Un producto digital vale por lo que hace posible después de publicarlo.</p></div><div className="pillar-grid">{items.map(([no, title, text]) => <div className="pillar" key={no}><span className="pillar-no">{no}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>; }

export function Approach() { const steps = [["01", "ENTENDEMOS", "Conocemos cómo funciona tu negocio y qué necesita resolver."], ["02", "DEFINIMOS", "Diseñamos estructura, solución y alcance antes de construir."], ["03", "CONSTRUIMOS", "Diseño y desarrollo con foco en una experiencia clara."], ["04", "ENTREGAMOS", "Publicamos y dejamos la solución preparada para utilizarse."]]; return <section className="approach"><div className="container"><span className="eyebrow">Método de trabajo</span><div className="approach-content"><div className="approach-big">Pensar.<br />Diseñar.<br /><span>Hacer.</span></div><div className="steps">{steps.map(([no, title, text]) => <div className="step" key={no}><span className="step-no">{no}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></div></section>; }

export function TechStack() { const groups = [["Frontend", "React\nNext.js\nTypeScript"], ["Backend", "Python\nNode.js\nJava"], ["Datos", "PostgreSQL\nMySQL\nSupabase"], ["Cloud", "Vercel\nCloudflare\nAzure"]]; return <section className="tech-section"><div className="container"><span className="eyebrow">Stack de respaldo</span><div className="tech-layout"><div className="tech-copy"><h2>Tecnología<br /><span className="orange">cuando importa.</span></h2><p>La herramienta adecuada para que la solución sea estable, escalable y fácil de usar. La tecnología acompaña la idea: no la tapa.</p></div><div className="tech-groups">{groups.map(([title, value]) => <div className="tech-group" key={title}><h3>{title}</h3><div>{value.split("\n").map(line => <div key={line}>{line}</div>)}</div></div>)}</div></div></div></section>; }

export function BeforeAfter() { const items = [["PDF por WhatsApp", "Catálogo navegable"], ["Información dispersa", "Web centralizada"], ["Consultas repetitivas", "Información disponible 24/7"], ["Procesos manuales", "Herramientas digitales"], ["Dependencia técnica", "Mayor control"]]; const [active, setActive] = useState(0); return <section className="before-after"><div className="container"><div className="section-heading"><div><span className="eyebrow">El cambio</span><h2 className="section-title">No se trata solo<br />de <span className="orange">verse mejor.</span></h2></div><p>Se trata de hacer que la información, los procesos y las oportunidades estén disponibles cuando el negocio los necesita.</p></div><div className="ba-grid">{items.map(([before, after], i) => <KeyboardButton variant="normal" className={`ba-item ${i === active ? "after" : "before"}`} key={before} onPress={() => setActive(i)} label={i === active ? after : before}><small>{i === active ? "FORM4TH" : "ANTES"}</small><h3>{i === active ? after : before}</h3></KeyboardButton>)}</div><p className="ba-hint">Selecciona una transformación para explorarla · {String(active + 1).padStart(2, "0")} / {String(items.length).padStart(2, "0")}</p></div></section>; }

export function ProjectHero({ type, title, image, external, externalLabel }: { type: string; title: string; image: string; external: string; externalLabel: string }) { return <section className="case-hero"><div className="container"><div className="case-top"><div><span className="eyebrow">Caso de estudio / {type}</span><h1>{title}</h1></div><div className="case-summary">Una necesidad concreta convertida en una experiencia digital más clara, accesible y preparada para el día a día.<br /><br /><KeyboardButton variant="enter" className="button-orange" href={external} external label={externalLabel} /></div></div><div className={`case-image ${title.includes("ACM") ? "acm" : "dj"}`}><Image src={image} alt={`Proyecto ${title}`} fill sizes="(max-width: 700px) 100vw, 1180px" priority /><div className="case-image-overlay"><span>FORM4TH / 2025</span><span>Scroll to explore ↓</span></div></div></div></section>; }

export function CasePreview({ label, image }: { label: string; image: string }) { return <section className="case-preview"><div className="container"><div className="case-preview-top"><span className="eyebrow">Diseño / Vista previa</span><span className="preview-note">Producto en contexto</span></div><div className="preview-frame"><Image src={image} alt={`Captura de ${label}`} fill sizes="(max-width: 700px) 100vw, 980px" /><div className="preview-window"><span /><span /><span /><b>{label}</b></div><div className="preview-label">FORM4TH / PRODUCT VIEW</div></div></div></section>; }
